CREATE DATABASE gvdcms;

USE gvdcms;  

CREATE TABLE users(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,	
user VARCHAR(64) NOT NULL,
password VARCHAR(64) NOT NULL
);

CREATE TABLE categories(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,	
category VARCHAR(64) NOT NULL
);

CREATE TABLE items(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,	
title VARCHAR(64) NOT NULL,
description TEXT NOT NULL,
imgPath TEXT NOT NULL,
mainImg TEXT NOT NULL,
category varchar(64) NOT NULL,
extra TEXT NOT NULL
);

INSERT INTO `users` (`id`, `user`, `password`) VALUES (NULL, 'admin', '$2y$10$arDVJ324Q/GtNhnNRyVuqun.6p1J9TGbmJJLbT1S4nvpw8bF819Xi');